Initial structure
daremove/go-musthave-diploma-tpl pull request #1
Opened 2024-03-25 19:00 UTC by daremove

2024-03-27 20:36 UTC, Bazys requested changes
1. Я всегда всех заставляю подключать goimport в проект
2. Не увидел ни одного теста, не хорошо, надо бы написать и поднять покрытие с 0 до как минимум 40
А в целом хороший зрелый код. Время еще есть, займись тестами

2024-03-27 20:36 UTC, Bazys commented on internal/middlewares/json.go
> +type RequestWithModel[Model ModelParameter] struct {
а зачем эта структура? не увидел ни одного использования

2024-03-27 20:36 UTC, Bazys commented on internal/services/job_queue.go
> +		go func(workerID int) {
а зачем параметр, если он не используется?

2024-03-27 20:36 UTC, Bazys commented on internal/services/order.go
> +	var result []models.Order
размер слайса *orders тебе известен, вставку в новый слайс делаешь без всяких условий, преаллоцируй массив заранее

2024-03-27 20:36 UTC, Bazys commented on internal/services/balance.go
> +	var result []models.WithdrawalFlowItem
тоже преаллокация.
Помните, в го есть GC и каждый раз когда вызывается аппенд в результате которго происходит переаллокация массива - это лишняя работа для сборщика мусора, а там есть такая вешь как StopTheWorld

2024-04-02 19:49 UTC, daremove commented
@Bazys  Поправил все комментарии. Добавил базовые тесты для слоя транспорта, не уверен, что успею покрыть вообще все, поэтому отдаю на ревью.

2024-04-03 10:09 UTC, Bazys approved these changes
35.1% тоже вполне хорошо.

2024-04-03 10:57 UTC, merged